WebViewer v11 Update
PDFTron/webviewer-generate-docx pull request #1
Opened 2024-11-13 21:55 UTC by carlolai

- Updated WebViewer to v11
- Changed to iFrame mode
- Updated ReadMe

2025-01-06 23:45 UTC, mparizeau-pdftron requested changes

2025-01-06 23:45 UTC, mparizeau-pdftron commented on src/components/Viewer.js
> +    WebViewer.Iframe(
With 11.1 it doesn't look like using the iframe should be necessary

2025-01-07 00:15 UTC, carlolai commented on src/components/Viewer.js
> +    WebViewer.Iframe(
Updated to 11.1 and switched it back to web-component mode.

2025-01-07 00:44 UTC, mparizeau-pdftron approved these changes

2025-01-07 00:44 UTC, merged